#!/bin/bash

if [ -z "$DOMAINS" ]; then
    echo "You have not set a DOMAINS environmental variable."
    exit 1
fi

if [ -z "$EMAIL" ]; then
    echo "You have not set an EMAIL environmental variable."
    exit 1
fi

HAPROXY_PID_FILE="/var/run/haproxy.pid"
HAPROXY_CONFIG_FILE="/usr/local/etc/haproxy/haproxy.cfg"
HAPROXY_CMD="haproxy -f $HAPROXY_CONFIG_FILE -p $HAPROXY_PID_FILE"
LETSENCRYPT_PORT="54321"
LETSENCRYPT_DIR="/opt/letsencrypt";
MAX_DAYS_LEFT_TO_EXPIRATION=30;

OPTION_LIST=""
IFS=',' read -ra DOMAIN_LIST <<< "$DOMAINS"
for i in "${DOMAIN_LIST[@]}"; do
    OPTION_LIST="$OPTION_LIST -d $i"
done
ROOT_DOMAIN=${DOMAIN_LIST[0]}

echo "Using root domain '$ROOT_DOMAIN'."

PRIVATE_KEY_FILE="/etc/letsencrypt/live/$ROOT_DOMAIN/privkey.pem"
CERTIFICATE_FILE="/etc/letsencrypt/live/$ROOT_DOMAIN/fullchain.pem"
COPY_PRIVATE_KEY_FILE="/usr/local/etc/haproxy/certs/$ROOT_DOMAIN/privkey.pem"
COPY_CERTIFICATE_FILE="/usr/local/etc/haproxy/certs/$ROOT_DOMAIN/fullchain.pem"
FULLCHAIN_FILE="/usr/local/etc/haproxy/certs/$ROOT_DOMAIN/$ROOT_DOMAIN.pem"

if [ ! -f $COPY_CERTIFICATE_FILE ]; then
    echo "[ERROR] certificate file not found for domain $ROOT_DOMAIN."
fi

create_certificate_files() {
    sudo bash -c "cat $PRIVATE_KEY_FILE $CERTIFICATE_FILE > $FULLCHAIN_FILE"
    sudo bash -c "cp $PRIVATE_KEY_FILE $COPY_PRIVATE_KEY_FILE"
    sudo bash -c "cp $CERTIFICATE_FILE $COPY_CERTIFICATE_FILE"
}

print_creating_certificates() {
    echo "Creating $FULLCHAIN_FILE and copy certificates to mounted volume..."
}

certificate_needs_update() {
    local expiration_time=$(date -d "`openssl x509 -in $COPY_CERTIFICATE_FILE -text -noout | grep "Not After" | cut -c 25-`" +%s)
    local now=$(date -d "now" +%s)
    local days_left_to_expiration=$(echo \( $expiration_time - $now \) / 86400 | bc)
    if [ "$days_left_to_expiration" -gt "$MAX_DAYS_LEFT_TO_EXPIRATION" ]; then
        echo "The certificate is up to date, no need for renewal ($days_left_to_expiration days left)."
        return 1
    else
        return 0
    fi
}

print_renewal_finish_statement() {
    echo "Renewal process finished for domain $ROOT_DOMAIN."
}

echo "Checking expiration date for $ROOT_DOMAIN..."

if certificate_needs_update; then
    mkdir -p /usr/local/etc/haproxy/certs/$ROOT_DOMAIN

    if [ -n "$INITIAL_RENEWAL" ]; then
        echo "Creating certificate..."
        $LETSENCRYPT_DIR/certbot-auto certonly --agree-tos --email $EMAIL --renew-by-default --rsa-key-size 4096 --standalone-supported-challenges http-01 $OPTION_LIST

        print_creating_certificates
        create_certificate_files
        print_renewal_finish_statement
    else
        echo "The certificate for $ROOT_DOMAIN is about to expire soon. Starting Let's Encrypt renewal script..."
        $LETSENCRYPT_DIR/certbot-auto certonly --agree-tos --email $EMAIL --renew-by-default --rsa-key-size 4096 --standalone-supported-challenges http-01 --http-01-port $LETSENCRYPT_PORT $OPTION_LIST

        print_creating_certificates
        create_certificate_files
        print_renewal_finish_statement
        $HAPROXY_CMD -sf $(cat $HAPROXY_PID_FILE)
    fi
fi
